name: CI

on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Ajustez selon la version de PHP utilisée

      - name: Install dependencies
        run: composer install

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=phpcs.xml src

      - name: Run PHPMD
        run: vendor/bin/phpmd src text phpmd.xml

      - name: Send coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
